build-venv:
	python -m venv venv

freeze:
	pip freeze | grep -v "pkg-resources" > requirements.txt

requirements-dev:
	pip install --upgrade pip
	pip install -r requirements.txt
	pip install twine

publish:
	python setup.py sdist
	twine upload dist/*

black:
	black flask_rest_crud -t py37 --line-length 79 --skip-string-normalization

black-check:
	black flask_rest_crud -t py37 --line-length 79 --skip-string-normalization --check

flake8:
	flake8 --show-source flask_rest_crud

lint:
    black flake8

lint-check:
    black-check flake8