build-venv:
	python -m venv venv

freeze:
	pip freeze | grep -v "pkg-resources" > requirements.txt

requirements-dev:
	pip install --upgrade pip
	pip install -r requirements.txt
	pip install twine

publish:
	python setup.py sdist
	twine upload dist/*
